In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
movies = pd.read_csv("movies.csv")

In [36]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [37]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   str
 2   genres   9742 non-null   str
dtypes: int64(1), str(2)
memory usage: 228.5 KB

In [38]:
movies['genres'] = movies['genres'].str.replace('|', ' ')

In [39]:
movies['title'] = movies['title'].str.replace(r"\(\d{4}\)$", "", regex=True).str.strip()
movies['title'] = movies['title'].str.capitalize()

In [40]:
movies.head()

,movieId,title,genres
0,1,Toy story,Adventure Animation Children Comedy Fantasy
1,2,Jumanji,Adventure Children Fantasy
2,3,Grumpier old men,Comedy Romance
3,4,Waiting to exhale,Comedy Drama Romance
4,5,Father of the bride part ii,Comedy

In [41]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['genres'])

In [42]:
similarity_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [43]:
indices = pd.Series(movies.index, index=movies['title'])

In [44]:
indices

title
Toy story                                0
Jumanji                                  1
Grumpier old men                         2
Waiting to exhale                        3
Father of the bride part ii              4
                                      ...
Black butler: book of the atlantic    9737
No game no life: zero                 9738
Flint                                 9739
Bungo stray dogs: dead apple          9740
Andrew dice clay: dice rules          9741
Length: 9742, dtype: int64

In [45]:
def recommend(movie_title):
    if movie_title not in indices:
        return "Movie not found in dataset"
    idx = indices[movie_title]
    sim_scores = list(enumerate(similarity_matrix[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:6]
    movie_indices = [i[0] for i in sim_scores]
    return movies['title'].iloc[movie_indices]

In [47]:
recommend("Pulp fiction")

520                                              Fargo
791                                            Freeway
2453    Man bites dog (c'est arrivé près de chez vous)
3155                               Beautiful creatures
4169                   Confessions of a dangerous mind
Name: title, dtype: str